// 389. Find the Difference
// Easy
// Topics
// premium lock icon
// Companies
// You are given two strings s and t.

// String t is generated by random shuffling string s and then add one more letter at a random position.

// Return the letter that was added to t.

// Example 1:

// Input: s = "abcd", t = "abcde"
// Output: "e"
// Explanation: 'e' is the letter that was added.
// Example 2:

// Input: s = "", t = "y"
// Output: "y"

// approach 1: nested loops
// class Solution {

//     public char findTheDifference(String s, String t) {

//         // Convert string s into a character array.
//         // We do this because we need to mark matched characters as used.
//         char[] letters = s.toCharArray();

//         // Traverse every character of string t.
//         for (int i = 0; i < t.length(); i++) {

//             // Assume the current character has not been found yet.
//             boolean found = false;

//             // Search the current character of t in the character array of s.
//             for (int j = 0; j < letters.length; j++) {

//                 // If the characters match
//                 if (t.charAt(i) == letters[j]) {

//                     // Character found
//                     found = true;

//                     // Mark this character as used so it cannot be matched again.
//                     letters[j] = '#';

//                     // Stop searching because we already found a match.
//                     break;
//                 }
//             }

//             // If the current character of t was not found in s,
//             // then this must be the extra character.
//             if (!found) {
//                 return t.charAt(i);
//             }
//         }

//         // This line will never be reached because the problem guarantees
//         // that t always contains exactly one extra character.
//         return ' ';
//     }
// }

//approach 2: frequency array
// class Solution {
//     public char findTheDifference(String s, String t) {

//         int[] count = new int[26];

//         // Count characters in s
//         for (int i = 0; i < s.length(); i++) {
//             count[s.charAt(i) - 'a']++;
//         }

//         // Remove characters using t
//         for (int i = 0; i < t.length(); i++) {

//             int index = t.charAt(i) - 'a';

//             count[index]--;

//             // If count becomes negative,
//             // this character was added.
//             if (count[index] < 0) {
//                 return t.charAt(i);
//             }
//         }

//         return ' ';
//     }
// }

// approach 3: exor property 
class Solution {
    public char findTheDifference(String s, String t) {

        char result = 0;

        for (int i = 0; i < s.length(); i++) {
            result ^= s.charAt(i);
        }

        for (int i = 0; i < t.length(); i++) {
            result ^= t.charAt(i);
        }

        return result;
    }
}

// Dry Run
// s = "abcd"

// t = "abcde"

// Initially

// result = 0

// After s

// 0 ^ a ^ b ^ c ^ d

// After t

// 0 ^ a ^ b ^ c ^ d
// ^ a ^ b ^ c ^ d ^ e

// Matching characters cancel out:

// a ^ a = 0

// b ^ b = 0

// c ^ c = 0

// d ^ d = 0

// Remaining

// 0 ^ e

// = e

// Return

// 'e'
// Complexity

// Time

// O(n)

// Space

// O(1)
// Which one should you use?
// Approach Time Space Interview Recommendation
// Nested Loops O(n²) O(1) ❌ No
// Frequency Array O(n) O(1) ✅ Excellent and easy to explain
// XOR O(n) O(1) ⭐ Best if you understand XOR